<a href="https://colab.research.google.com/github/hashir910/Data-Science/blob/main/numpy/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [181]:
import pandas as pd
import numpy as np

narr=np.array([1.0,2.1,3.32,4.99,5.10])
narr

array([1.  , 2.1 , 3.32, 4.99, 5.1 ])

In [182]:
# arthimetic

print(narr+10)
print(narr*10)
print(narr/10)
print(narr**10)
print(narr-10)

[11.   12.1  13.32 14.99 15.1 ]
[10.  21.  33.2 49.9 51. ]
[0.1   0.21  0.332 0.499 0.51 ]
[1.00000000e+00 1.66798810e+03 1.62697484e+05 9.57206097e+06
 1.19042424e+07]
[-9.   -7.9  -6.68 -5.01 -4.9 ]


In [183]:
# built in methods
print(narr)
print(np.sqrt(narr))
print(np.round(narr))
print(np.floor(narr))
print(np.ceil(narr))


[1.   2.1  3.32 4.99 5.1 ]
[1.         1.44913767 1.82208672 2.23383079 2.25831796]
[1. 2. 3. 5. 5.]
[1. 2. 3. 4. 5.]
[1. 3. 4. 5. 6.]


In [184]:
#vectorized methods
narr2=np.array([6,7,8,9,10])

print(np.round(narr)+narr2)
print(np.round(narr)-narr2)
print(np.round(narr)/narr2)
print(np.round(narr)*narr2)
print(np.round(narr)**narr2)

[ 7.  9. 11. 14. 15.]
[-5. -5. -5. -4. -5.]
[0.16666667 0.28571429 0.375      0.55555556 0.5       ]
[ 6. 14. 24. 45. 50.]
[1.000000e+00 1.280000e+02 6.561000e+03 1.953125e+06 9.765625e+06]


In [185]:
# comparision operator

print(narr>10)
print(narr<10)
print(narr==10)
print(narr!=10)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [186]:

narr2

array([ 6,  7,  8,  9, 10])

In [188]:
narr2[(narr2-7==2)&(narr2==9)]=88
narr2

array([ 6,  7,  8, 88, 10])