<a href="https://colab.research.google.com/github/hashir910/Data-Science/blob/main/numpy/day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

random no

In [3]:
import pandas as pd
import numpy as np

arr1=np.array([[[1],[2],[3]],
               [[1],[2],[3]]])
arr1.shape

(2, 3, 1)

In [4]:
arr1

array([[[1],
        [2],
        [3]],

       [[1],
        [2],
        [3]]])

In [19]:
# random integers------------------

rang=np.random.default_rng()
print(rang.integers(1,5))
print(rang.integers(1,101))
print(rang.integers(1,101,size=3))
print(rang.integers(1,101,size=(3,4)))

2
43
[71 96 43]
[[81 34 62 47]
 [ 9 42 88 45]
 [20 85 10 15]]


In [37]:
# random choice-------------------

rng=np.random.default_rng()
arr2=np.array([1,2,3,4,5])
choic=rng.choice(arr2)
choic=rng.choice(arr2,size=3)
choic=rng.choice(arr2,size=(3,2))
print(choic)

[[4 3]
 [5 5]
 [2 1]]


In [39]:
# shuffle

rng.shuffle(arr2)
arr2


array([5, 4, 3, 1, 2])