<a href="https://colab.research.google.com/github/hashir910/Data-Science/blob/main/numpy/day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**broad casting**////

In [88]:
import numpy as np


# 1.one of the dimension should have to one
# 2.both the dimension should be equal

In [89]:
# arr1=np.array([[1,2,3,4,5],
#               [6,7,8,9,10]])
# arr2=np.array([[1],[2],[3],[4]])
# print(arr1.shape)
# print(arr2.shape)
# print(arr1+arr2)

In [90]:
arr1=np.array([[1,2,3,4]])
arr2=np.array([[1],[2],[3],[4]])
print(arr1.shape)
print(arr2.shape)
print(arr1+arr2)

(1, 4)
(4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [91]:
arr3=np.array([[1,2,3,4]])
arr4=np.array([[1],[2],[3],[4]])
print(arr1.shape)
print(arr2.shape)
print(arr1*arr2)
print(list(range(1,len(arr4)+1)))


(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[1, 2, 3, 4]


In [92]:
import pandas as pd

df=pd.DataFrame(arr3*arr4,columns=list(range(1,len(arr4)+1)))
df

1  2   3   4
0  1  2   3   4
1  2  4   6   8
2  3  6   9  12
3  4  8  12  16

**aggregate functions**

In [93]:
arr3=np.array([[1,2,3,4]])
arr4=np.array([[1],[2],[3],[4],
              [1],[2],[3],[4]])

print(arr3.sum())
print(arr4.mean())
print(arr4.std())
print(arr4.var())

10
2.5
1.118033988749895
1.25


In [97]:
print(np.sum(arr3))
print(np.sum(arr4,axis=0))
print(np.sum(arr4,axis=1))
print(np.mean(arr4,axis=0))
print(np.mean(arr4,axis=1))
print(np.std(arr4,axis=1))
print(np.std(arr4,axis=0))

10
[20]
[1 2 3 4 1 2 3 4]
[2.5]
[1. 2. 3. 4. 1. 2. 3. 4.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1.11803399]
